DROP SCHEMA IF EXISTS GTRI_ITWMA_DB;
/*DROP SCHEMA IF EXISTS GTRI_ITWMA_DB_DEV;*/
DROP DATABASE IF EXISTS GTRI_ITWA_DB;
/*DROP DATABASE IF EXISTS GTRI_ITWA_DB_DEV;*/

CREATE DATABASE GTRI_ITWMA_DB;
/*CREATE DATABASE GTRI_ITWMA_DB_DEV;*/